//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRESTACONNECT.WSVERSION {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Version", Namespace="http://www.prestaconnect.fr/")]
    [System.SerializableAttribute()]
    public partial class Version : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        private int ValueField;
        
        private int SageField;
        
        private int PrestashopField;
        
        private int TargetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Sage {
            get {
                return this.SageField;
            }
            set {
                if ((this.SageField.Equals(value) != true)) {
                    this.SageField = value;
                    this.RaisePropertyChanged("Sage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Prestashop {
            get {
                return this.PrestashopField;
            }
            set {
                if ((this.PrestashopField.Equals(value) != true)) {
                    this.PrestashopField = value;
                    this.RaisePropertyChanged("Prestashop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Target {
            get {
                return this.TargetField;
            }
            set {
                if ((this.TargetField.Equals(value) != true)) {
                    this.TargetField = value;
                    this.RaisePropertyChanged("Target");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.prestaconnect.fr/", ConfigurationName="WSVERSION.WSVersionSoap")]
    public interface WSVersionSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorldResult de l'espace de noms http://www.prestaconnect.fr/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prestaconnect.fr/HelloWorld", ReplyAction="*")]
        PRESTACONNECT.WSVERSION.HelloWorldResponse HelloWorld(PRESTACONNECT.WSVERSION.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prestaconnect.fr/ExistVersion", ReplyAction="*")]
        bool ExistVersion(uint current, int sage, int prestashop);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément ReadVersionResult de l'espace de noms http://www.prestaconnect.fr/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prestaconnect.fr/ReadVersion", ReplyAction="*")]
        PRESTACONNECT.WSVERSION.ReadVersionResponse ReadVersion(PRESTACONNECT.WSVERSION.ReadVersionRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément product de l'espace de noms http://www.prestaconnect.fr/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prestaconnect.fr/ExistVersionProduct", ReplyAction="*")]
        PRESTACONNECT.WSVERSION.ExistVersionProductResponse ExistVersionProduct(PRESTACONNECT.WSVERSION.ExistVersionProductRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément product de l'espace de noms http://www.prestaconnect.fr/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prestaconnect.fr/ReadVersionProduct", ReplyAction="*")]
        PRESTACONNECT.WSVERSION.ReadVersionProductResponse ReadVersionProduct(PRESTACONNECT.WSVERSION.ReadVersionProductRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://www.prestaconnect.fr/", Order=0)]
        public PRESTACONNECT.WSVERSION.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(PRESTACONNECT.WSVERSION.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://www.prestaconnect.fr/", Order=0)]
        public PRESTACONNECT.WSVERSION.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(PRESTACONNECT.WSVERSION.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prestaconnect.fr/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadVersion", Namespace="http://www.prestaconnect.fr/", Order=0)]
        public PRESTACONNECT.WSVERSION.ReadVersionRequestBody Body;
        
        public ReadVersionRequest() {
        }
        
        public ReadVersionRequest(PRESTACONNECT.WSVERSION.ReadVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prestaconnect.fr/")]
    public partial class ReadVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint current;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int prestashop;
        
        public ReadVersionRequestBody() {
        }
        
        public ReadVersionRequestBody(uint current, int sage, int prestashop) {
            this.current = current;
            this.sage = sage;
            this.prestashop = prestashop;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadVersionResponse", Namespace="http://www.prestaconnect.fr/", Order=0)]
        public PRESTACONNECT.WSVERSION.ReadVersionResponseBody Body;
        
        public ReadVersionResponse() {
        }
        
        public ReadVersionResponse(PRESTACONNECT.WSVERSION.ReadVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prestaconnect.fr/")]
    public partial class ReadVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PRESTACONNECT.WSVERSION.Version ReadVersionResult;
        
        public ReadVersionResponseBody() {
        }
        
        public ReadVersionResponseBody(PRESTACONNECT.WSVERSION.Version ReadVersionResult) {
            this.ReadVersionResult = ReadVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistVersionProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistVersionProduct", Namespace="http://www.prestaconnect.fr/", Order=0)]
        public PRESTACONNECT.WSVERSION.ExistVersionProductRequestBody Body;
        
        public ExistVersionProductRequest() {
        }
        
        public ExistVersionProductRequest(PRESTACONNECT.WSVERSION.ExistVersionProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prestaconnect.fr/")]
    public partial class ExistVersionProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string product;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint current;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int sage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int prestashop;
        
        public ExistVersionProductRequestBody() {
        }
        
        public ExistVersionProductRequestBody(string product, uint current, int sage, int prestashop) {
            this.product = product;
            this.current = current;
            this.sage = sage;
            this.prestashop = prestashop;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistVersionProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistVersionProductResponse", Namespace="http://www.prestaconnect.fr/", Order=0)]
        public PRESTACONNECT.WSVERSION.ExistVersionProductResponseBody Body;
        
        public ExistVersionProductResponse() {
        }
        
        public ExistVersionProductResponse(PRESTACONNECT.WSVERSION.ExistVersionProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prestaconnect.fr/")]
    public partial class ExistVersionProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ExistVersionProductResult;
        
        public ExistVersionProductResponseBody() {
        }
        
        public ExistVersionProductResponseBody(bool ExistVersionProductResult) {
            this.ExistVersionProductResult = ExistVersionProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadVersionProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadVersionProduct", Namespace="http://www.prestaconnect.fr/", Order=0)]
        public PRESTACONNECT.WSVERSION.ReadVersionProductRequestBody Body;
        
        public ReadVersionProductRequest() {
        }
        
        public ReadVersionProductRequest(PRESTACONNECT.WSVERSION.ReadVersionProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prestaconnect.fr/")]
    public partial class ReadVersionProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string product;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint current;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int sage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int prestashop;
        
        public ReadVersionProductRequestBody() {
        }
        
        public ReadVersionProductRequestBody(string product, uint current, int sage, int prestashop) {
            this.product = product;
            this.current = current;
            this.sage = sage;
            this.prestashop = prestashop;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadVersionProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadVersionProductResponse", Namespace="http://www.prestaconnect.fr/", Order=0)]
        public PRESTACONNECT.WSVERSION.ReadVersionProductResponseBody Body;
        
        public ReadVersionProductResponse() {
        }
        
        public ReadVersionProductResponse(PRESTACONNECT.WSVERSION.ReadVersionProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prestaconnect.fr/")]
    public partial class ReadVersionProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PRESTACONNECT.WSVERSION.Version ReadVersionProductResult;
        
        public ReadVersionProductResponseBody() {
        }
        
        public ReadVersionProductResponseBody(PRESTACONNECT.WSVERSION.Version ReadVersionProductResult) {
            this.ReadVersionProductResult = ReadVersionProductResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSVersionSoapChannel : PRESTACONNECT.WSVERSION.WSVersionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSVersionSoapClient : System.ServiceModel.ClientBase<PRESTACONNECT.WSVERSION.WSVersionSoap>, PRESTACONNECT.WSVERSION.WSVersionSoap {
        
        public WSVersionSoapClient() {
        }
        
        public WSVersionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSVersionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSVersionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSVersionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRESTACONNECT.WSVERSION.HelloWorldResponse PRESTACONNECT.WSVERSION.WSVersionSoap.HelloWorld(PRESTACONNECT.WSVERSION.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            PRESTACONNECT.WSVERSION.HelloWorldRequest inValue = new PRESTACONNECT.WSVERSION.HelloWorldRequest();
            inValue.Body = new PRESTACONNECT.WSVERSION.HelloWorldRequestBody();
            PRESTACONNECT.WSVERSION.HelloWorldResponse retVal = ((PRESTACONNECT.WSVERSION.WSVersionSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        public bool ExistVersion(uint current, int sage, int prestashop) {
            return base.Channel.ExistVersion(current, sage, prestashop);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRESTACONNECT.WSVERSION.ReadVersionResponse PRESTACONNECT.WSVERSION.WSVersionSoap.ReadVersion(PRESTACONNECT.WSVERSION.ReadVersionRequest request) {
            return base.Channel.ReadVersion(request);
        }
        
        public PRESTACONNECT.WSVERSION.Version ReadVersion(uint current, int sage, int prestashop) {
            PRESTACONNECT.WSVERSION.ReadVersionRequest inValue = new PRESTACONNECT.WSVERSION.ReadVersionRequest();
            inValue.Body = new PRESTACONNECT.WSVERSION.ReadVersionRequestBody();
            inValue.Body.current = current;
            inValue.Body.sage = sage;
            inValue.Body.prestashop = prestashop;
            PRESTACONNECT.WSVERSION.ReadVersionResponse retVal = ((PRESTACONNECT.WSVERSION.WSVersionSoap)(this)).ReadVersion(inValue);
            return retVal.Body.ReadVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRESTACONNECT.WSVERSION.ExistVersionProductResponse PRESTACONNECT.WSVERSION.WSVersionSoap.ExistVersionProduct(PRESTACONNECT.WSVERSION.ExistVersionProductRequest request) {
            return base.Channel.ExistVersionProduct(request);
        }
        
        public bool ExistVersionProduct(string product, uint current, int sage, int prestashop) {
            PRESTACONNECT.WSVERSION.ExistVersionProductRequest inValue = new PRESTACONNECT.WSVERSION.ExistVersionProductRequest();
            inValue.Body = new PRESTACONNECT.WSVERSION.ExistVersionProductRequestBody();
            inValue.Body.product = product;
            inValue.Body.current = current;
            inValue.Body.sage = sage;
            inValue.Body.prestashop = prestashop;
            PRESTACONNECT.WSVERSION.ExistVersionProductResponse retVal = ((PRESTACONNECT.WSVERSION.WSVersionSoap)(this)).ExistVersionProduct(inValue);
            return retVal.Body.ExistVersionProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRESTACONNECT.WSVERSION.ReadVersionProductResponse PRESTACONNECT.WSVERSION.WSVersionSoap.ReadVersionProduct(PRESTACONNECT.WSVERSION.ReadVersionProductRequest request) {
            return base.Channel.ReadVersionProduct(request);
        }
        
        public PRESTACONNECT.WSVERSION.Version ReadVersionProduct(string product, uint current, int sage, int prestashop) {
            PRESTACONNECT.WSVERSION.ReadVersionProductRequest inValue = new PRESTACONNECT.WSVERSION.ReadVersionProductRequest();
            inValue.Body = new PRESTACONNECT.WSVERSION.ReadVersionProductRequestBody();
            inValue.Body.product = product;
            inValue.Body.current = current;
            inValue.Body.sage = sage;
            inValue.Body.prestashop = prestashop;
            PRESTACONNECT.WSVERSION.ReadVersionProductResponse retVal = ((PRESTACONNECT.WSVERSION.WSVersionSoap)(this)).ReadVersionProduct(inValue);
            return retVal.Body.ReadVersionProductResult;
        }
    }
}
