//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRESTACONNECT.WSKEYRESCUE {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Key", Namespace="http://www.prestaconnect.fr/")]
    [System.SerializableAttribute()]
    public partial class Key : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DealerField;
        
        private System.DateTime DUADateField;
        
        private int SageField;
        
        private int PrestashopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BDDSageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BDDPrestaconnectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BDDPrestashopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomainField;
        
        private bool Option1Field;
        
        private bool Option2Field;
        
        private bool Option3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LicenseKey {
            get {
                return this.LicenseKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseKeyField, value) != true)) {
                    this.LicenseKeyField = value;
                    this.RaisePropertyChanged("LicenseKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Dealer {
            get {
                return this.DealerField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerField, value) != true)) {
                    this.DealerField = value;
                    this.RaisePropertyChanged("Dealer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime DUADate {
            get {
                return this.DUADateField;
            }
            set {
                if ((this.DUADateField.Equals(value) != true)) {
                    this.DUADateField = value;
                    this.RaisePropertyChanged("DUADate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Sage {
            get {
                return this.SageField;
            }
            set {
                if ((this.SageField.Equals(value) != true)) {
                    this.SageField = value;
                    this.RaisePropertyChanged("Sage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Prestashop {
            get {
                return this.PrestashopField;
            }
            set {
                if ((this.PrestashopField.Equals(value) != true)) {
                    this.PrestashopField = value;
                    this.RaisePropertyChanged("Prestashop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string BDDSage {
            get {
                return this.BDDSageField;
            }
            set {
                if ((object.ReferenceEquals(this.BDDSageField, value) != true)) {
                    this.BDDSageField = value;
                    this.RaisePropertyChanged("BDDSage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string BDDPrestaconnect {
            get {
                return this.BDDPrestaconnectField;
            }
            set {
                if ((object.ReferenceEquals(this.BDDPrestaconnectField, value) != true)) {
                    this.BDDPrestaconnectField = value;
                    this.RaisePropertyChanged("BDDPrestaconnect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string BDDPrestashop {
            get {
                return this.BDDPrestashopField;
            }
            set {
                if ((object.ReferenceEquals(this.BDDPrestashopField, value) != true)) {
                    this.BDDPrestashopField = value;
                    this.RaisePropertyChanged("BDDPrestashop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Domain {
            get {
                return this.DomainField;
            }
            set {
                if ((object.ReferenceEquals(this.DomainField, value) != true)) {
                    this.DomainField = value;
                    this.RaisePropertyChanged("Domain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool Option1 {
            get {
                return this.Option1Field;
            }
            set {
                if ((this.Option1Field.Equals(value) != true)) {
                    this.Option1Field = value;
                    this.RaisePropertyChanged("Option1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool Option2 {
            get {
                return this.Option2Field;
            }
            set {
                if ((this.Option2Field.Equals(value) != true)) {
                    this.Option2Field = value;
                    this.RaisePropertyChanged("Option2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool Option3 {
            get {
                return this.Option3Field;
            }
            set {
                if ((this.Option3Field.Equals(value) != true)) {
                    this.Option3Field = value;
                    this.RaisePropertyChanged("Option3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.prestaconnect.fr/", ConfigurationName="WSKEYRESCUE.WSKeySoap")]
    public interface WSKeySoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorldResult de l'espace de noms http://www.prestaconnect.fr/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prestaconnect.fr/HelloWorld", ReplyAction="*")]
        PRESTACONNECT.WSKEYRESCUE.HelloWorldResponse HelloWorld(PRESTACONNECT.WSKEYRESCUE.HelloWorldRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément Key de l'espace de noms http://www.prestaconnect.fr/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prestaconnect.fr/ExistKey", ReplyAction="*")]
        PRESTACONNECT.WSKEYRESCUE.ExistKeyResponse ExistKey(PRESTACONNECT.WSKEYRESCUE.ExistKeyRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément Key de l'espace de noms http://www.prestaconnect.fr/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prestaconnect.fr/ReadKey", ReplyAction="*")]
        PRESTACONNECT.WSKEYRESCUE.ReadKeyResponse ReadKey(PRESTACONNECT.WSKEYRESCUE.ReadKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prestaconnect.fr/GetNow", ReplyAction="*")]
        System.DateTime GetNow();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://www.prestaconnect.fr/", Order=0)]
        public PRESTACONNECT.WSKEYRESCUE.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(PRESTACONNECT.WSKEYRESCUE.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://www.prestaconnect.fr/", Order=0)]
        public PRESTACONNECT.WSKEYRESCUE.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(PRESTACONNECT.WSKEYRESCUE.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prestaconnect.fr/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistKey", Namespace="http://www.prestaconnect.fr/", Order=0)]
        public PRESTACONNECT.WSKEYRESCUE.ExistKeyRequestBody Body;
        
        public ExistKeyRequest() {
        }
        
        public ExistKeyRequest(PRESTACONNECT.WSKEYRESCUE.ExistKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prestaconnect.fr/")]
    public partial class ExistKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Key;
        
        public ExistKeyRequestBody() {
        }
        
        public ExistKeyRequestBody(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistKeyResponse", Namespace="http://www.prestaconnect.fr/", Order=0)]
        public PRESTACONNECT.WSKEYRESCUE.ExistKeyResponseBody Body;
        
        public ExistKeyResponse() {
        }
        
        public ExistKeyResponse(PRESTACONNECT.WSKEYRESCUE.ExistKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prestaconnect.fr/")]
    public partial class ExistKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ExistKeyResult;
        
        public ExistKeyResponseBody() {
        }
        
        public ExistKeyResponseBody(bool ExistKeyResult) {
            this.ExistKeyResult = ExistKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadKey", Namespace="http://www.prestaconnect.fr/", Order=0)]
        public PRESTACONNECT.WSKEYRESCUE.ReadKeyRequestBody Body;
        
        public ReadKeyRequest() {
        }
        
        public ReadKeyRequest(PRESTACONNECT.WSKEYRESCUE.ReadKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prestaconnect.fr/")]
    public partial class ReadKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Key;
        
        public ReadKeyRequestBody() {
        }
        
        public ReadKeyRequestBody(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadKeyResponse", Namespace="http://www.prestaconnect.fr/", Order=0)]
        public PRESTACONNECT.WSKEYRESCUE.ReadKeyResponseBody Body;
        
        public ReadKeyResponse() {
        }
        
        public ReadKeyResponse(PRESTACONNECT.WSKEYRESCUE.ReadKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prestaconnect.fr/")]
    public partial class ReadKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PRESTACONNECT.WSKEYRESCUE.Key ReadKeyResult;
        
        public ReadKeyResponseBody() {
        }
        
        public ReadKeyResponseBody(PRESTACONNECT.WSKEYRESCUE.Key ReadKeyResult) {
            this.ReadKeyResult = ReadKeyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSKeySoapChannel : PRESTACONNECT.WSKEYRESCUE.WSKeySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSKeySoapClient : System.ServiceModel.ClientBase<PRESTACONNECT.WSKEYRESCUE.WSKeySoap>, PRESTACONNECT.WSKEYRESCUE.WSKeySoap {
        
        public WSKeySoapClient() {
        }
        
        public WSKeySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSKeySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSKeySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSKeySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRESTACONNECT.WSKEYRESCUE.HelloWorldResponse PRESTACONNECT.WSKEYRESCUE.WSKeySoap.HelloWorld(PRESTACONNECT.WSKEYRESCUE.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            PRESTACONNECT.WSKEYRESCUE.HelloWorldRequest inValue = new PRESTACONNECT.WSKEYRESCUE.HelloWorldRequest();
            inValue.Body = new PRESTACONNECT.WSKEYRESCUE.HelloWorldRequestBody();
            PRESTACONNECT.WSKEYRESCUE.HelloWorldResponse retVal = ((PRESTACONNECT.WSKEYRESCUE.WSKeySoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRESTACONNECT.WSKEYRESCUE.ExistKeyResponse PRESTACONNECT.WSKEYRESCUE.WSKeySoap.ExistKey(PRESTACONNECT.WSKEYRESCUE.ExistKeyRequest request) {
            return base.Channel.ExistKey(request);
        }
        
        public bool ExistKey(string Key) {
            PRESTACONNECT.WSKEYRESCUE.ExistKeyRequest inValue = new PRESTACONNECT.WSKEYRESCUE.ExistKeyRequest();
            inValue.Body = new PRESTACONNECT.WSKEYRESCUE.ExistKeyRequestBody();
            inValue.Body.Key = Key;
            PRESTACONNECT.WSKEYRESCUE.ExistKeyResponse retVal = ((PRESTACONNECT.WSKEYRESCUE.WSKeySoap)(this)).ExistKey(inValue);
            return retVal.Body.ExistKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRESTACONNECT.WSKEYRESCUE.ReadKeyResponse PRESTACONNECT.WSKEYRESCUE.WSKeySoap.ReadKey(PRESTACONNECT.WSKEYRESCUE.ReadKeyRequest request) {
            return base.Channel.ReadKey(request);
        }
        
        public PRESTACONNECT.WSKEYRESCUE.Key ReadKey(string Key) {
            PRESTACONNECT.WSKEYRESCUE.ReadKeyRequest inValue = new PRESTACONNECT.WSKEYRESCUE.ReadKeyRequest();
            inValue.Body = new PRESTACONNECT.WSKEYRESCUE.ReadKeyRequestBody();
            inValue.Body.Key = Key;
            PRESTACONNECT.WSKEYRESCUE.ReadKeyResponse retVal = ((PRESTACONNECT.WSKEYRESCUE.WSKeySoap)(this)).ReadKey(inValue);
            return retVal.Body.ReadKeyResult;
        }
        
        public System.DateTime GetNow() {
            return base.Channel.GetNow();
        }
    }
}
